name: Deploy application onto AWS servers

on:
    # Only trigger this workflow when it is called or manually executed
    workflow_dispatch:
    workflow_call:

jobs:
    containerise-application:
        name: Containerising App
        uses: ./.github/workflows/containerise_application.yml

    deploy-container:
        name: Deploying Container
        needs: containerise-application
        uses: ./.github/workflows/deploy_container.yml